package youtube_transcript

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
)

const (
	// apifyActorCallTimeout is the timeout for each Apify actor call.
	apifyActorCallTimeout = 120 * time.Second
)

// --- Actor configurations (tried in order) ---

// apifyActorDef describes a single Apify actor to try as part of the fallback chain.
type apifyActorDef struct {
	name    string
	apiPath string // e.g. "codepoetry~youtube-transcript-ai-scraper"
	// buildInput builds the JSON request body for this actor.
	buildInput func(videoURL, preferredLang string) any
	// extractResult extracts a transcript result from the first dataset item.
	// Returns nil item if this actor returned a non-fatal error (try next actor).
	extractResult func(item json.RawMessage) *apifyFallbackResult
}

// apifyFallbackResult holds the common fields we need from whichever actor succeeded.
type apifyFallbackResult struct {
	TranscriptText string
	TranscriptLLM  string
	Language       string
	IsAutoGenerated bool
	IsAIGenerated   bool
	Error          string
	ErrorCode      string
}

// actorFallbackChain is the ordered list of actors to try.
var actorFallbackChain = []apifyActorDef{
	{
		name:    "codepoetry/youtube-transcript-ai-scraper",
		apiPath: "codepoetry~youtube-transcript-ai-scraper",
		buildInput: func(videoURL, preferredLang string) any {
			languages := buildLanguageList(preferredLang)
			return map[string]any{
				"startUrls": []map[string]any{
					{"url": videoURL},
				},
				"languages":       languages,
				"outputFormats":   []string{"text", "llm"},
				"enableAiFallback": false,
			}
		},
		extractResult: extractCodepoetryResult,
	},
	{
		name:    "supreme_coder/youtube-transcript-scraper",
		apiPath: "supreme_coder~youtube-transcript-scraper",
		buildInput: func(videoURL, preferredLang string) any {
			return map[string]any{
				"urls":         []string{videoURL},
				"outputFormat": "text",
			}
		},
		extractResult: extractGenericResult,
	},
	{
		name:    "scrape-creators/best-youtube-transcripts-scraper",
		apiPath: "scrape-creators~best-youtube-transcripts-scraper",
		buildInput: func(videoURL, preferredLang string) any {
			return map[string]any{
				"urls": []string{videoURL},
			}
		},
		extractResult: extractGenericResult,
	},
}

// buildLanguageList returns the ordered list of languages to request.
func buildLanguageList(preferredLang string) []string {
	languages := []string{"de", "en"}
	if preferredLang != "" && !strings.EqualFold(preferredLang, "de") && !strings.EqualFold(preferredLang, "en") {
		languages = []string{preferredLang, "de", "en"}
	} else if strings.EqualFold(preferredLang, "en") {
		languages = []string{"en", "de"}
	}
	return languages
}

// extractCodepoetryResult parses the response from codepoetry~youtube-transcript-ai-scraper.
func extractCodepoetryResult(raw json.RawMessage) *apifyFallbackResult {
	var item struct {
		URL      string `json:"url,omitempty"`
		Error    string `json:"error,omitempty"`
		ErrorCode string `json:"error_code,omitempty"`

		Language         string `json:"language,omitempty"`
		IsAutoGenerated  bool   `json:"is_auto_generated,omitempty"`
		IsAIGenerated    bool   `json:"is_ai_generated,omitempty"`
		TranscriptText   string `json:"transcript_text,omitempty"`
		TranscriptLLM    string `json:"transcript_llm,omitempty"`
	}
	if err := json.Unmarshal(raw, &item); err != nil {
		return nil
	}
	return &apifyFallbackResult{
		TranscriptText:  item.TranscriptText,
		TranscriptLLM:   item.TranscriptLLM,
		Language:        item.Language,
		IsAutoGenerated: item.IsAutoGenerated,
		IsAIGenerated:   item.IsAIGenerated,
		Error:           item.Error,
		ErrorCode:       item.ErrorCode,
	}
}

// extractGenericResult is a lenient parser for actors whose exact output format
// we don't know. It looks for common transcript text fields.
func extractGenericResult(raw json.RawMessage) *apifyFallbackResult {
	var item map[string]any
	if err := json.Unmarshal(raw, &item); err != nil {
		return nil
	}

	result := &apifyFallbackResult{}

	// Try common error fields
	if err, _ := item["error"].(string); err != "" {
		result.Error = err
	}
	if code, _ := item["error_code"].(string); code != "" {
		result.ErrorCode = code
	}

	// Try common transcript text field names
	for _, key := range []string{"transcript_text", "text", "transcript", "plainText", "content"} {
		if v, ok := item[key].(string); ok && v != "" {
			result.TranscriptText = v
			break
		}
	}

	// Try language field
	if lang, _ := item["language"].(string); lang != "" {
		result.Language = lang
	} else if lang, _ := item["lang"].(string); lang != "" {
		result.Language = lang
	}

	// Try auto-generated flags
	if v, _ := item["is_auto_generated"].(bool); v {
		result.IsAutoGenerated = v
	}
	if v, _ := item["is_ai_generated"].(bool); v {
		result.IsAIGenerated = v
	}

	return result
}

// --- Provider ---

// ApifyProvider implements YouTubeTranscriptProvider using a fallback chain
// of Apify actors for YouTube transcript extraction.
type ApifyProvider struct {
	apiKey    string
	actors    []apifyActorDef
	client    *http.Client
	actorName string // name of the last successfully used actor
}

// NewApifyProvider creates a new Apify-based YouTube transcript provider.
func NewApifyProvider(apiKey string) (interfaces.YouTubeTranscriptProvider, error) {
	if apiKey == "" {
		return nil, fmt.Errorf("APIFY_API_KEY is required for Apify provider")
	}
	return &ApifyProvider{
		apiKey: apiKey,
		actors: actorFallbackChain,
		client: &http.Client{Timeout: apifyActorCallTimeout},
	}, nil
}

// Name returns the provider name.
func (p *ApifyProvider) Name() string {
	if p.actorName != "" {
		return "apify/" + p.actorName
	}
	return "apify"
}

// apifyMetadata is the metadata structure returned by codepoetry's actor.
type apifyMetadata struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	URL         string   `json:"url"`
	Channel     string   `json:"channel"`
	ChannelID   string   `json:"channel_id"`
	ChannelURL  string   `json:"channel_url"`
	Description string   `json:"description"`
	Duration    int      `json:"duration"`
	ViewCount   int64    `json:"view_count"`
	LikeCount   int64    `json:"like_count"`
	UploadDate  string   `json:"upload_date"`
	Thumbnail   string   `json:"thumbnail"`
	Tags        []string `json:"tags"`
	Categories  []string `json:"categories"`
}

// FetchMetadata fetches video metadata via the Apify actor chain.
// It tries each actor until one returns metadata successfully.
func (p *ApifyProvider) FetchMetadata(ctx context.Context, videoID string) (*types.YouTubeMetadataResult, error) {
	// Metadata comes from the codepoetry actor's native response format.
	// For simplicity, we do a full transcript call and extract metadata
	// from the first successful actor that returns it.
	type metaHolder struct {
		Metadata *apifyMetadata `json:"metadata,omitempty"`
	}

	for _, actor := range p.actors {
		items, err := p.callActor(ctx, actor, videoID, "")
		if err != nil {
			continue
		}
		if len(items) == 0 {
			continue
		}

		var holder metaHolder
		if err := json.Unmarshal(items[0], &holder); err != nil || holder.Metadata == nil {
			continue
		}

		p.actorName = actor.name
		return mapMetadata(holder.Metadata, videoID), nil
	}

	return nil, fmt.Errorf("all Apify actors failed to fetch metadata for video %s", videoID)
}

// FetchTranscript fetches the transcript via the Apify actor fallback chain.
// It tries each actor in order; if one fails with a recoverable error
// (LANGUAGE_NOT_FOUND, empty transcript, etc.) it proceeds to the next.
func (p *ApifyProvider) FetchTranscript(ctx context.Context, videoID string, preferredLang string) (*types.YouTubeTranscriptResult, error) {
	videoURL := fmt.Sprintf("https://www.youtube.com/watch?v=%s", videoID)
	var lastErr error

	for _, actor := range p.actors {
		result, err := p.tryActorTranscript(ctx, actor, videoURL, preferredLang)
		if err != nil {
			lastErr = err
			continue
		}
		if result != nil {
			p.actorName = actor.name
			return result, nil
		}
	}

	return nil, fmt.Errorf("all Apify actors failed for video %s: %w", videoID, lastErr)
}

// tryActorTranscript attempts to fetch a transcript from a single actor.
func (p *ApifyProvider) tryActorTranscript(ctx context.Context, actor apifyActorDef, videoURL, preferredLang string) (*types.YouTubeTranscriptResult, error) {
	items, err := p.callActor(ctx, actor, videoURL, preferredLang)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", actor.name, err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("%s: returned no data", actor.name)
	}

	result := actor.extractResult(items[0])
	if result == nil {
		return nil, fmt.Errorf("%s: could not parse response", actor.name)
	}

	if result.Error != "" {
		return nil, fmt.Errorf("%s: %s (code: %s)", actor.name, result.Error, result.ErrorCode)
	}

	// Prefer transcript_llm (filler-stripped), fall back to transcript_text
	content := result.TranscriptLLM
	if content == "" {
		content = result.TranscriptText
	}
	if content == "" {
		return nil, fmt.Errorf("%s: returned empty transcript", actor.name)
	}

	source := "native"
	if result.IsAIGenerated {
		source = "ai_generated"
	} else if result.IsAutoGenerated {
		source = "auto_generated"
	}

	return &types.YouTubeTranscriptResult{
		Content:       content,
		Language:      result.Language,
		Source:        source,
		IsAIGenerated: result.IsAIGenerated,
	}, nil
}

// callActor calls a single Apify actor synchronously and returns the raw dataset items.
func (p *ApifyProvider) callActor(ctx context.Context, actor apifyActorDef, videoURL, preferredLang string) ([]json.RawMessage, error) {
	input := actor.buildInput(videoURL, preferredLang)
	body, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("marshal input: %w", err)
	}

	apiURL := fmt.Sprintf("https://api.apify.com/v2/acts/%s/run-sync-get-dataset-items?token=%s", actor.apiPath, p.apiKey)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, apiURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := p.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return nil, fmt.Errorf("API returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var items []json.RawMessage
	if err := json.Unmarshal(respBody, &items); err != nil {
		return nil, fmt.Errorf("decode response: %w (body: %s)", err, string(respBody))
	}

	return items, nil
}

// mapMetadata maps Apify metadata to our internal YouTubeMetadataResult.
func mapMetadata(m *apifyMetadata, videoID string) *types.YouTubeMetadataResult {
	return &types.YouTubeMetadataResult{
		VideoID:      videoID,
		Title:        m.Title,
		ChannelName:  m.Channel,
		ChannelURL:   m.ChannelURL,
		Duration:     m.Duration,
		ThumbnailURL: m.Thumbnail,
		Description:  m.Description,
		PublishedAt:  m.UploadDate,
		Tags:         m.Tags,
	}
}

// Ensure compile-time interface conformance
var _ interfaces.YouTubeTranscriptProvider = (*ApifyProvider)(nil)
