package youtube_transcript

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
)

const (
	// apifySyncRunURL is the Apify API endpoint for running an actor synchronously
	// and getting dataset items. The actor ID is "codepoetry~youtube-transcript-ai-scraper".
	apifySyncRunURL = "https://api.apify.com/v2/acts/codepoetry~youtube-transcript-ai-scraper/run-sync-get-dataset-items"

	// apifyActorCallTimeout is the timeout for the Apify sync API call.
	// The actor processes videos concurrently (up to 5), so a single video should
	// complete well within this window. For AI transcription, longer videos may take
	// more time (~8× real-time for AI, but we keep AI off by default).
	apifyActorCallTimeout = 120 * time.Second
)

// ApifyProvider implements YouTubeTranscriptProvider using the Apify
// codepoetry/youtube-transcript-ai-scraper actor.
type ApifyProvider struct {
	apiKey  string
	baseURL string
	client  *http.Client
}

// NewApifyProvider creates a new Apify-based YouTube transcript provider.
func NewApifyProvider(apiKey string) (interfaces.YouTubeTranscriptProvider, error) {
	if apiKey == "" {
		return nil, fmt.Errorf("APIFY_API_KEY is required for Apify provider")
	}
	return &ApifyProvider{
		apiKey:  apiKey,
		baseURL: apifySyncRunURL,
		client:  &http.Client{Timeout: apifyActorCallTimeout},
	}, nil
}

// Name returns the provider name.
func (p *ApifyProvider) Name() string { return "apify" }

// apifyInput is the input schema for the youtube-transcript-ai-scraper actor.
type apifyInput struct {
	StartUrls    []apifyStartURL `json:"startUrls"`
	Languages    []string        `json:"languages"`
	OutputFormats []string       `json:"outputFormats"`
	EnableAiFallback bool        `json:"enableAiFallback"`
	MaxResults   int             `json:"maxResults,omitempty"`
}

type apifyStartURL struct {
	URL string `json:"url"`
}

// apifyOutputItem represents a single item in the Apify dataset response.
type apifyOutputItem struct {
	URL      string          `json:"url,omitempty"`
	Error    string          `json:"error,omitempty"`
	ErrorCode string         `json:"error_code,omitempty"`

	Metadata *apifyMetadata  `json:"metadata,omitempty"`

	Language         string `json:"language,omitempty"`
	IsAutoGenerated  bool   `json:"is_auto_generated,omitempty"`
	IsAIGenerated    bool   `json:"is_ai_generated,omitempty"`

	TranscriptText   string `json:"transcript_text,omitempty"`
	TranscriptLLM    string `json:"transcript_llm,omitempty"`
}

type apifyMetadata struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	URL         string   `json:"url"`
	Channel     string   `json:"channel"`
	ChannelID   string   `json:"channel_id"`
	ChannelURL  string   `json:"channel_url"`
	Description string   `json:"description"`
	Duration    int      `json:"duration"`
	ViewCount   int64    `json:"view_count"`
	LikeCount   int64    `json:"like_count"`
	UploadDate  string   `json:"upload_date"`
	Thumbnail   string   `json:"thumbnail"`
	Tags        []string `json:"tags"`
	Categories  []string `json:"categories"`
}

// FetchMetadata fetches video metadata via the Apify actor.
// Since the Apify actor returns both metadata and transcript in one call,
// we make a full request and extract only the metadata part.
func (p *ApifyProvider) FetchMetadata(ctx context.Context, videoID string) (*types.YouTubeMetadataResult, error) {
	items, err := p.callApifyActor(ctx, videoID, "")
	if err != nil {
		return nil, err
	}

	if len(items) == 0 {
		return nil, fmt.Errorf("Apify returned no data for video %s", videoID)
	}

	item := items[0]
	if item.Error != "" {
		return nil, fmt.Errorf("Apify returned error for video %s: %s (code: %s)", videoID, item.Error, item.ErrorCode)
	}

	if item.Metadata == nil {
		return nil, fmt.Errorf("Apify returned no metadata for video %s", videoID)
	}

	return p.mapMetadata(item.Metadata, videoID), nil
}

// FetchTranscript fetches the transcript via the Apify actor.
func (p *ApifyProvider) FetchTranscript(ctx context.Context, videoID string, preferredLang string) (*types.YouTubeTranscriptResult, error) {
	items, err := p.callApifyActor(ctx, videoID, preferredLang)
	if err != nil {
		return nil, err
	}

	if len(items) == 0 {
		return nil, fmt.Errorf("Apify returned no data for video %s", videoID)
	}

	item := items[0]
	if item.Error != "" {
		return nil, fmt.Errorf("Apify returned error for video %s: %s (code: %s)", videoID, item.Error, item.ErrorCode)
	}

	// Prefer transcript_llm (filler-stripped, AI-ready), fall back to transcript_text
	content := item.TranscriptLLM
	if content == "" {
		content = item.TranscriptText
	}
	if content == "" {
		return nil, fmt.Errorf("Apify returned empty transcript for video %s", videoID)
	}

	source := "native"
	if item.IsAIGenerated {
		source = "ai_generated"
	} else if item.IsAutoGenerated {
		source = "auto_generated"
	}

	return &types.YouTubeTranscriptResult{
		Content:       content,
		Language:      item.Language,
		Source:        source,
		IsAIGenerated: item.IsAIGenerated,
	}, nil
}

// callApifyActor calls the Apify actor synchronously and returns the dataset items.
func (p *ApifyProvider) callApifyActor(ctx context.Context, videoID string, preferredLang string) ([]apifyOutputItem, error) {
	videoURL := fmt.Sprintf("https://www.youtube.com/watch?v=%s", videoID)

	// Build language list: preferred first, then "en" as fallback
	languages := []string{"en"}
	if preferredLang != "" && !strings.EqualFold(preferredLang, "en") {
		languages = []string{preferredLang, "en"}
	}

	input := apifyInput{
		StartUrls: []apifyStartURL{
			{URL: videoURL},
		},
		Languages:        languages,
		OutputFormats:    []string{"text", "llm"},
		EnableAiFallback: false, // default off to control costs; native captions only
	}

	body, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("marshal Apify input: %w", err)
	}

	apiURL := fmt.Sprintf("%s?token=%s", p.baseURL, p.apiKey)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, apiURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create Apify request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := p.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Apify request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read Apify response: %w", err)
	}

	// Apify sync API returns 200 or 201 on success
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return nil, fmt.Errorf("Apify API returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var items []apifyOutputItem
	if err := json.Unmarshal(respBody, &items); err != nil {
		return nil, fmt.Errorf("decode Apify response: %w (body: %s)", err, string(respBody))
	}

	return items, nil
}

// mapMetadata maps Apify metadata to our internal YouTubeMetadataResult.
func (p *ApifyProvider) mapMetadata(m *apifyMetadata, videoID string) *types.YouTubeMetadataResult {
	result := &types.YouTubeMetadataResult{
		VideoID:      videoID,
		Title:        m.Title,
		ChannelName:  m.Channel,
		ChannelURL:   m.ChannelURL,
		Duration:     m.Duration,
		ThumbnailURL: m.Thumbnail,
		Description:  m.Description,
		PublishedAt:  m.UploadDate,
		Tags:         m.Tags,
	}

	return result
}

// Ensure compile-time interface conformance
var _ interfaces.YouTubeTranscriptProvider = (*ApifyProvider)(nil)
